language: ruby
sudo: false
addons:
  postgresql: 9.4
rvm:
  - 2.3.1
  - ruby-head
gemfile:
  - Gemfile
  - Gemfile.edge
bundler_args: -j4 --without production development
before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - bundle exec rake db:create ridgepole:apply RAILS_ENV=test
  - npm install
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: Gemfile.edge
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4378570d751369a7fb6
    on_success: always
    on_failure: always
    on_start: true
