language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - ruby-head
bundler_args: --deployment -j4 --without production development
before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=1
before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - bundle exec rake db:migrate RAILS_ENV=test
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4378570d751369a7fb6
    on_success: always
    on_failure: always
    on_start: true
